os: linux
dist: focal
language: generic

env:
  jobs:
    - LISP=abcl
    - LISP=allegro
    - LISP=ccl
    - LISP=ccl32
    - LISP=clisp
    # clisp:i386 no longer available in Ubuntu Focal
    # - LISP=clisp32
    # cmucl not supported by CIM
    # - LISP=cmucl
    - LISP=ecl
    - LISP=sbcl
    - LISP=sbcl32

jobs:
  fast_finish: true
  allow_failures:
    - env: LISP=abcl
    - env: LISP=allegro
    - env: LISP=ccl32
    - env: LISP=clisp
    # - env: LISP=clisp32
    # - env: LISP=cmucl
    - env: LISP=ecl
    - env: LISP=sbcl32

install:
  - curl -L https://github.com/lispci/cl-travis/raw/master/install.sh | sh
  - git clone --depth=1 https://github.com/trivial-features/trivial-features.git ~/lisp/trivial-features
  - git clone https://gitlab.common-lisp.net/alexandria/alexandria.git ~/lisp/alexandria
  - git clone --depth=1 https://github.com/cl-babel/babel.git ~/lisp/babel

script:
  - cl -e '(ql:quickload :cffi-tests)
           (when (cffi-tests:run-all-cffi-tests)
             (uiop:quit 1))'
